name: Deploy Real Estate Prices

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (для Svelte)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Svelte frontend
        working-directory: ./landing
        run: |
          npm install
          npm run build

      - name: Build and push Docker image for backend
        working-directory: ./backend
        run: |
          docker build -t real-estate-prices-backend:latest .
          docker save real-estate-prices-backend:latest -o real-estate-prices-backend.tar

      - name: Archive project files
        run: |
          tar -czvf real-estate-prices.tar.gz real-estate-prices-backend.tar frontend/build

      - name: Copy files to Server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: real-estate-prices.tar.gz
          target: ~/deployments/

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deployments
            tar -xzvf real-estate-prices.tar.gz

            # Deploy Frontend
            rm -rf /var/www/html/*
            cp -r frontend/build/* /var/www/html/

            # Deploy Backend Docker Image
            docker load -i real-estate-prices-backend.tar
            docker stop real_estate_prices_backend || true
            docker rm real_estate_prices_backend || true
            docker run -d --name real_estate_prices_backend -p 8000:8000 real-estate-prices-backend:latest
